Admin.PlantDiseaseX/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PlantDiseaseX.Core;
using PlantDiseaseX.Core.Entities;
using PlantDiseaseX.Repository;
namespace Admin.PlantDiseaseX.Controllers
{
    [Authorize]

    public class CategoryController : Controller
    {
        private readonly IToastNotification _toastNotification;

        private readonly IUnitOfWork unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork , IToastNotification toastNotification)
        {
            this._toastNotification = toastNotification;
            this.unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var Categories = await unitOfWork.Repository<Plantcategory>().GetAllAsync();
            return View(Categories);
        }



        [HttpPost]
        public async Task<IActionResult> Create(Plantcategory category)
        {
            try
            {
                await unitOfWork.Repository<Plantcategory>().AddAsync(category);
                await unitOfWork.Complete();
                _toastNotification.AddSuccessToastMessage("Category Created Successfully");
                return RedirectToAction("Index");
            }
            catch (System.Exception)
            {
                ModelState.AddModelError("Name", "Please Enter A New Category");
                return View("index", await unitOfWork.Repository<Plantcategory>().GetAllAsync());
            }
        }


        public async Task<IActionResult> Delete(int id)
        {
            var category = await unitOfWork.Repository<Plantcategory>().GetByIdAsync(id);
            unitOfWork.Repository<Plantcategory>().Delete(category);
            await unitOfWork.Complete();

            _toastNotification.AddErrorToastMessage("Category Deleted Successfully");

            return RedirectToAction("index");
        }
    }
}

Admin.PlantDiseaseX/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PlantDiseaseX.Core;
using PlantDiseaseX.Core.Entities;

namespace Admin.PlantDiseaseX.Controllers
{
    [Authorize]

    public class ContactUsController : Controller
    {

        private readonly IToastNotification _toastNotification;

        private readonly IUnitOfWork unitOfWork;


        public ContactUsController(IUnitOfWork unitOfWork, IToastNotification toastNotification)
        {
            this._toastNotification = toastNotification;
            this.unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var Contacts = await unitOfWork.Repository<ContactUs>().GetAllAsync();

            return View(Contacts);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var contactus = await unitOfWork.Repository<ContactUs>().GetByIdAsync(id);
            unitOfWork.Repository<ContactUs>().Delete(contactus);
            await unitOfWork.Complete();

            _toastNotification.AddSuccessToastMessage("Contact Deleted Successfully");

            return RedirectToAction("index");
        }
    }
}

Admin.PlantDiseaseX/Controllers/HomeController.cs
using Admin.PlantDiseaseX.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlantDiseaseX.Core;
using PlantDiseaseX.Repository;
using System.Diagnostics;
using static StackExchange.Redis.Role;
using Admin.PlantDiseaseX.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using PlantDiseaseX.Core.Repositories;
using AutoMapper;
using System.Threading.Tasks;
using System.Collections.Generic;
using PlantDiseaseX.Core.Entities;
using plantdiseasex.core.entities;
using PlantDiseaseX.Core.Repositories;
using Admin.PlantDiseaseX.Repository;
using Admin.PlantDiseaseX.Services; // Adjust namespace as per your project structure


namespace Admin.PlantDiseaseX.Controllers
{
    [Authorize]
    
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserRepository _userRepository;
        private readonly IUserService _userService;

        public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork, IMapper mapper, UserRepository userRepository, IUserService userService)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userRepository = userRepository;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var plants = await _unitOfWork.Repository<Plant>().GetAllAsync();
            var mappedPlants = _mapper.Map<IReadOnlyList<Plant>, IReadOnlyList<PlantViewModel>>(plants);

            var categories = await _unitOfWork.Repository<Plantcategory>().GetAllAsync();
            var mappedCategories = _mapper.Map<IReadOnlyList<Plantcategory>,IReadOnlyList<CategoryViewModel>>(categories);
           
            
            var seasons = await _unitOfWork.Repository<Season>().GetAllAsync();
            var mappedSeasons = _mapper.Map<IReadOnlyList<Season>, IReadOnlyList<SeasonViewModel>>(seasons);


            var NewsArticles = await _unitOfWork.Repository<NewsArticle>().GetAllAsync();
            var mappedNewsArticles = _mapper.Map<IReadOnlyList<NewsArticle>, IReadOnlyList<NewsArticleViewModel>>(NewsArticles);

            var CornDiseases = await _unitOfWork.Repository<corndisease>().GetAllAsync();
            var mappedCornDiseases = _mapper.Map<IReadOnlyList<corndisease>, IReadOnlyList<CornDiseasecsViewModel>>(CornDiseases);


            var messages = await _unitOfWork.Repository<ContactUs>().GetAllAsync();
            var mappedMessages = _mapper.Map<IReadOnlyList<ContactUs>, IReadOnlyList<ContactUsViewModel>>(messages);


            var signedInUsersCount = await _userRepository.GetSignedInUsersCountAsync();
            ViewBag.SignedInUsersCount = signedInUsersCount;


            var loggedInUsers = await _userService.GetCurrentlyLoggedInUsersAsync();
            ViewBag.LoggedInUsers = loggedInUsers;

            var viewModel = new HomeIndexViewModel
            {
                Plants = mappedPlants,
                Categories = mappedCategories,
                Seasons = mappedSeasons,
                NewsArticles = mappedNewsArticles,
                CornDiseases = mappedCornDiseases,
                Messages = mappedMessages

            };

            return View(viewModel);


           // return View(mappedPlants,mappedNewsArticles,mappedCornDiseases);
        }
      
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Admin.PlantDiseaseX/Controllers/PlantController.cs
using Admin.PlantDiseaseX.Helper;
using Admin.PlantDiseaseX.Models;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using PlantDiseaseX.Core;
using PlantDiseaseX.Core.Entities;
using PlantDiseaseX.Core.Repositories;
using PlantDiseaseX.Repository.Data;
using System.Collections.Generic;
using PlantDiseaseX.API.Dtos;
using NToastNotify;
using PlantDiseaseX.Core.Specifications;
using Microsoft.AspNetCore.Authorization;


namespace Admin.PlantDiseaseX.Controllers
{
    [Authorize]

    public class PlantController : Controller
    {
        private readonly IToastNotification _toastNotification;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;


        public PlantController(IUnitOfWork unitOfWork, IMapper mapper, IToastNotification toastNotification)
        {
            _toastNotification = toastNotification;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var plants = await _unitOfWork.Repository<Plant>().GetAllAsync();
                var mappedplants = _mapper.Map<IReadOnlyList<Plant>, IReadOnlyList<PlantViewModel>>(plants);

                return View(mappedplants);
            }
            else
            {
                var specParams = new PlantSpecParams { Search = SearchValue};
                var spec = new PlantWithCategoryAndSeasonSpecification(specParams);
                var plants = await _unitOfWork.Repository<Plant>().GetAllWithSpecAsync(spec);
                var mappedplants = _mapper.Map<IReadOnlyList<Plant>, IReadOnlyList<PlantViewModel>>(plants);

                return View(mappedplants);
            }
        }





        public IActionResult Create()
        {

            return View();
        }

       



        [HttpPost]

        public async Task<IActionResult> Create(PlantViewModel model)
        {


            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            if (ModelState.IsValid)
            {


                if (model.Image != null)
                    model.PictureUrl = PictureSettings.UploadFile(model.Image, "plants");
                else
                    model.PictureUrl = "images/plants/DefaultImage.jpg";

                var mappedPlant = _mapper.Map<PlantViewModel, Plant>(model);
                await _unitOfWork.Repository<Plant>().AddAsync(mappedPlant);

                await _unitOfWork.Complete();


                _toastNotification.AddSuccessToastMessage("Plant Created Successfully");

                return RedirectToAction("Index");
            }



            // If ModelState.IsValid is false, ensure that PictureUrl is initialized
            if (model.PictureUrl == null)
            {
                model.PictureUrl = "images/plants/DefaultImage.png";
            }


            return View(model);

        }



        public async Task<IActionResult> Edit(int id)
        {
            var plant = await _unitOfWork.Repository<Plant>().GetByIdAsync(id);
            var mappedPlant = _mapper.Map<Plant, PlantViewModel>(plant);
            return View("Edit", mappedPlant);
        }



       






        [HttpPost]
        public async Task<IActionResult> Edit(int id, PlantViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != model.Id)
                return NotFound();
            if (ModelState.IsValid)
            {
                if (model.Image != null)
                {
                    if (model.PictureUrl != null)
                    {
                        PictureSettings.DeleteFile(model.PictureUrl, "plants");
                        model.PictureUrl = PictureSettings.UploadFile(model.Image, "plants");
                    }
                    else
                    {
                        model.PictureUrl = PictureSettings.UploadFile(model.Image, "plants");

                    }

                }
                var mappedPlant = _mapper.Map<PlantViewModel, Plant>(model);
                _unitOfWork.Repository<Plant>().Update(mappedPlant);
                var result = await _unitOfWork.Complete();
                if (result > 0)
                {
                    _toastNotification.AddSuccessToastMessage("Plant Updated Successfully");

                    return RedirectToAction("Index");
                }
            }
            return View("Edit", model);
        }



        public async Task<IActionResult> Delete(int id)
        {
            var plant = await _unitOfWork.Repository<Plant>().GetByIdAsync(id);
            var mappedPlant = _mapper.Map<Plant, PlantViewModel>(plant);
            return View(mappedPlant);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id, PlantViewModel model)
        {
            if (id != model.Id)
                return NotFound();
            try
            {
                var plant = await _unitOfWork.Repository<Plant>().GetByIdAsync(id);
                if (plant.PictureUrl != null)
                    PictureSettings.DeleteFile(plant.PictureUrl, "plants");



                _unitOfWork.Repository<Plant>().Delete(plant);
                await _unitOfWork.Complete();

              
                _toastNotification.AddErrorToastMessage("Plant Deleted Successfully");

                // return Ok();
                return RedirectToAction("Index");

            }
            catch (System.Exception)
            {

                return View(model);
            }
        }


        public async Task<IActionResult> Details(int id)
        {
            var plant = await _unitOfWork.Repository<Plant>().GetByIdAsync(id);
            var mappedPlant = _mapper.Map<Plant, PlantViewModel>(plant);
            return View(mappedPlant);
        }


    }
}

Admin.PlantDiseaseX/Controllers/SeasonController.cs
using Microsoft.AspNetCore.Mvc;
using PlantDiseaseX.Core.Entities;
using PlantDiseaseX.Core;
using NToastNotify;
using Microsoft.AspNetCore.Authorization;

namespace Admin.PlantDiseaseX.Controllers
{
    [Authorize]

    public class SeasonController : Controller
    {
        private readonly IToastNotification _toastNotification;

        private readonly IUnitOfWork unitOfWork;

        public SeasonController(IUnitOfWork unitOfWork, IToastNotification toastNotification)
        {
            this._toastNotification = toastNotification;
            this.unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var Seasons = await unitOfWork.Repository<Season>().GetAllAsync();
            return View(Seasons);
        }



        [HttpPost]
        public async Task<IActionResult> Create(Season season)
        {
            try
            {
                await unitOfWork.Repository<Season>().AddAsync(season);
                await unitOfWork.Complete();
                _toastNotification.AddSuccessToastMessage("Season Created Successfully");
                return RedirectToAction("Index");
            }
            catch (System.Exception)
            {
                ModelState.AddModelError("Name", "Please Enter A New Season");
                return View("index", await unitOfWork.Repository<Season>().GetAllAsync());
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            var season = await unitOfWork.Repository<Season>().GetByIdAsync(id);
            unitOfWork.Repository<Season>().Delete(season);
            await unitOfWork.Complete();
            _toastNotification.AddErrorToastMessage("Season Deleted Successfully");

            return RedirectToAction("index");
        }
    }
}

Admin.PlantDiseaseX/Views/Home/Index.cshtml
@model Admin.PlantDiseaseX.Controllers.HomeIndexViewModel



<div class="container">
    <div class="row">

        <div class="col-md-12" id="clock">

            <p class="date">{{ date }}</p>
            <p class="time">{{ time }}</p>
            <p class="text">Graduation Project</p>

        </div>

        
        
        <hr class="mt-3 bg-black" />
        <p class="mt-3">Users.... <br /> </p>

        <div class="col-md-5 mt-4 py-4 mx-2" style="background-color:#00b45b !important">
            <a asp-controller="Home" asp-action="Index">
                <p>Currently Logged-In Users:</p>
            </a>
            @if (ViewBag.LoggedInUsers != null && ViewBag.LoggedInUsers.Count > 0)
            {
                <ul>
                    @foreach (ApplicationUser user in ViewBag.LoggedInUsers)
                    {
                        <li> Full_Name :  @user.FName  @user.LName <br /></li>
                        <li> Email: @user.Email </li>
                    }
                </ul>
            }
            else
            {
                <p>No users currently logged in</p>
            }
        </div>



        <div class="col-md-3 mt-4 py-4 mx-2" style="background-color:#00b45b !important">
            <a asp-controller="Home" asp-action="Index">
                <p>Total Users Signed In: <br /></p>
                <ul>
                    <li>  @ViewBag.SignedInUsersCount </li>
                </ul>
            </a>
        </div>

        <hr class="mt-3 bg-black" />
          <p class="mt-3">Main.... <br /> </p>
        <div class="col-md-3 mt-4 py-4 mx-2" style="background-color:#00b45b8a !important">

            <a asp-controller="Plant" asp-action="Index">
                <p >Total Plants: <br /> </p>
                <ul>
                    <li> @Model.Plants.Count</li>
                </ul>
            </a>
        </div>
        <div class="col-md-3 mt-4 py-4 mx-2" style="background-color:#ff000094 !important">
            <a asp-controller="NewsArticle" asp-action="Index">
                <p>Total News Articles: <br /> </p>
                <ul>
                    <li>@Model.NewsArticles.Count</li>
                </ul>
            </a>
        </div>
        <div class="col-md-3 mt-4 py-4 mx-2 " style="background-color:#1d8cf8bd">
            <a asp-controller="CornDisease" asp-action="Index">
                <p>Total Corn Diseases: <br /> </p>
                <ul>
                    <li>@Model.CornDiseases.Count</li>
                </ul>
            </a>
        </div>

        <hr class="mt-3 bg-black" />

        <p class="mt-3">Realted Plant.... <br /> </p>
        <div class="col-md-3 mt-4 py-4 mx-2 " style="background-color:#72e1ff52 !important">
            <a asp-controller="Category" asp-action="Index">
                <p>Total Categories: <br /> </p>
                <ul>
                    <li>@Model.Categories.Count</li>
                </ul>
            </a>
        </div>

        <div class="col-md-3 mt-4 py-4 mx-2 " style="background-color:#1a61ab80">
            <a asp-controller="Season" asp-action="Index">
                <p>Total Seasons: <br /> </p>
                <ul>
                    <li>@Model.Seasons.Count</li>
                </ul>
            </a>
        </div>
        <hr class="mt-3 bg-black " />
        <p class="mt-3">Users Messages.... <br /> </p>

        <div class="col-md-3 mt-4 py-4 mx-2 " style="background-color:#adb5bd75">
            <a asp-controller="ContactUs" asp-action="Index">
                <p>Total Messages: <br /> </p>
                <ul>
                    <li>@Model.Messages.Count</li>
                </ul>
            </a>
        </div>
    </div>



</div>



<style>
    html, body {
        height: 100%;
    }

    body {
        background: #0f3854;
        background: radial-gradient(ellipse at center, #0a2e38 0%, #000000 70%);
        background-size: 100%;
    }

    p {
        margin: 0;
        padding: 0;
    }

    #clock {
        font-family: 'Share Tech Mono', monospace;
        color: #daf6ff;
        text-align: center;
        position: relative;
        left: 570px;
        top: 100px;
        transform: translate(-50%, -50%);
        text-shadow: 0 0 20px rgba(10, 175, 230, 1), 0 0 20px rgba(10, 175, 230, 0);
    }

    .time {
        letter-spacing: 0.05em;
        font-size: 80px;
        padding: 5px 0;
    }

    .date {
        letter-spacing: 0.1em;
        font-size: 24px;
    }

    .text {
        letter-spacing: 0.1em;
        font-size: 25px;
        padding: 25px 0 0;
    }

    .container {
        font-size: 20px
    }

    .col-md-3 {
        border-radius: 3%
    }

        .col-md-3:hover {
            transform: translate(-5px, -10px);
        }


     .col-md-5{
            border-radius: 3%
     }

      .col-md-5:hover {
            transform: translate(-5px, -10px);
        }


</style>

@section scripts {
    <script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
    <script>
        var clock = new Vue({
            el: '#clock',
            data: {
                time: '',
                date: ''
            }
        });

        var week = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'];
        var timerID = setInterval(updateTime, 1000);
        updateTime();
        function updateTime() {
            var cd = new Date();
            var hours = cd.getHours();
            var ampm = hours >= 12 ? 'PM' : 'AM';
            hours = hours % 12;
            hours = hours ? hours : 12; // 12-hour clock with 0 representing 12
            clock.time = zeroPadding(hours, 2) + ':' + zeroPadding(cd.getMinutes(), 2) + ':' + zeroPadding(cd.getSeconds(), 2) + ' ' + ampm;
            clock.date = zeroPadding(cd.getFullYear(), 4) + '-' + zeroPadding(cd.getMonth() + 1, 2) + '-' + zeroPadding(cd.getDate(), 2) + ' ' + week[cd.getDay()];
        };

        function zeroPadding(num, digit) {
            var zero = '';
            for (var i = 0; i < digit; i++) {
                zero += '0';
            }
            return (zero + num).slice(-digit);
        }
    </script>
}